import Head from "next/head";
import Navbar from "@/components/Navbar";

const Transformers: React.FC<{}> = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main>
        <Navbar />
      </main>
    </>
  );
};

export default Transformers;
